.github/workflows/dev.yml
Makefile_libs.mk

- Added 'on-tag' parameters to control workflow execution on specific tags, improving flexibility.
- Replaced hardcoded secrets with GitHub context variables for secure and maintainable credential management.

Enhance Workflow Tagging Strategy and Security in CI Pipeline

---

platform/f2/activity-f2/activity-f2-api/src/main/kotlin/io/komune/registry/f2/activity/api/model/StepExtension.kt
platform/f2/activity-f2/activity-f2-api/src/main/kotlin/io/komune/registry/f2/activity/api/service/ActivityF2FinderService.kt
platform/f2/asset-pool-f2/asset-pool-f2-api/src/main/kotlin/io/komune/registry/f2/asset/pool/api/model/AssetPoolDTOExtension.kt
platform/f2/asset-pool-f2/asset-pool-f2-api/src/main/kotlin/io/komune/registry/f2/asset/pool/api/service/AssetPoolF2FinderService.kt
platform/s2/project/project-api/src/main/kotlin/io/komune/registry/s2/project/api/ProjectAggregateService.kt
platform/script/script-init/src/test/kotlin/cee/CeeConcepts.kt
platform/script/script-init/src/test/kotlin/cee/baten101/Concepts.kt
platform/script/script-init/src/test/kotlin/cee/indba116/Concepts.kt

Simplified the model hierarchy by replacing InformationConceptBase with InformationConcept. This refactor improves maintainability, ensures consistency, and enhances code readability across the codebase.

refactor(api): replace InformationConceptBase with InformationConcept

---

Makefile_libs.mk
buildSrc/src/main/kotlin/Dependencies.kt
infra/docker-compose/.env_dev
infra/docker-compose/docker-compose-keycloak.yml
infra/docker-compose/docker-compose-postgres.yml
infra/docker-compose/scripts/create-multiple-databases.sh
platform/api/api-config/build.gradle.kts
platform/api/api-config/src/main/resources/application.yml
platform/api/api-gateway/src/main/kotlin/io/komune/registry/api/gateway/RegisterApplication.kt
platform/data/s2/catalogue/catalogue-api/build.gradle.kts
platform/data/s2/catalogue/catalogue-api/src/main/kotlin/io/komune/registry/program/s2/catalogue/api/config/CatalogueAutomateConfig.kt
platform/data/s2/dataset/dataset-api/build.gradle.kts
platform/data/s2/dataset/dataset-api/src/main/kotlin/io/komune/registry/program/s2/dataset/api/config/DatasetAutomateConfig.kt
platform/project/s2/asset/asset-api/build.gradle.kts
platform/project/s2/asset/asset-api/src/main/kotlin/io/komune/registry/s2/asset/api/entity/pool/AssetPoolAutomateConfig.kt
platform/project/s2/asset/asset-api/src/main/kotlin/io/komune/registry/s2/asset/api/entity/transaction/AssetTransactionAutomateConfig.kt
platform/project/s2/order/order-api/build.gradle.kts
platform/project/s2/order/order-api/src/main/kotlin/io/komune/registry/s2/order/api/entity/OrderAutomateConfig.kt
platform/project/s2/project/project-api/build.gradle.kts
platform/project/s2/project/project-api/src/main/kotlin/io/komune/registry/s2/project/api/config/ProjectAutomateConfig.kt
platform/project/test/src/test/kotlin/io/komune/registry/project/test/bdd/RunProjectCucumberTest.kt
platform/project/test/src/test/kotlin/io/komune/registry/project/test/bdd/SpringProjectTestConfiguration.kt
platform/project/test/src/test/kotlin/io/komune/registry/project/test/bdd/TestProjectApplication.kt
platform/project/test/src/test/resources/io.komune.registry.project.test.bdd/s2/asset/command/AssetPoolEmitTransaction.feature

This merge request introduces PostgreSQL integration with R2DBC for reactive database access, including Docker Compose configuration for initializing multiple databases. It also enhances the test suite by adding Cucumber tests for API functionality.

Add PostgreSQL Support with R2DBC and Cucumber API Tests

---

Makefile_docker.mk
infra/docker-compose/dev-compose.mk
infra/docker-compose/docker-compose-c2-sandbox-ssm.yml
infra/docker-compose/docker-compose-c2-sandbox.yml
infra/docker-compose/docker-compose-cccev.yml
infra/docker-compose/docker-compose-connect-admin.yml
infra/docker-compose/docker-compose-fs.yml
infra/docker-compose/docker-compose-im-config.yml
infra/docker-compose/docker-compose-im-init.yml
infra/docker-compose/docker-compose-im.yml
infra/docker-compose/docker-compose-kb.yml
infra/docker-compose/docker-compose-keycloak.yml
infra/docker-compose/docker-compose-postgres.yml
infra/docker-compose/docker-compose-redis.yml
infra/docker-compose/docker-compose-registry-init.yml
infra/docker/postgres/Dockerfile
infra/docker/postgres/scripts/create-multiple-databases.sh

The changes introduce PostgreSQL as a new service in the Docker setup, including a Dockerfile and a script for creating multiple databases. This allows for better management of database instances and enhances the application's ability to handle multiple environments or projects. Additionally, the integration of environment files across various services improves configuration management and consistency.

feat(docker): add PostgreSQL support with Docker integration and multiple database creation script

---

Makefile_docker.mk
infra/docker-compose/docker-compose-postgres.yml

refactor(docker): streamline Docker build commands and add promote functionality
The PostgreSQL image reference is updated to use a specific version, ensuring consistency in deployments. The Docker build commands are refactored for better readability and maintainability. Additionally, a promote task is added to facilitate the promotion of Docker images, enhancing the overall build process.

chore(docker): update PostgreSQL image reference and improve Docker build commands

---

infra/docker/postgres/Dockerfile

The Postgres image is updated to the latest version to take advantage of new features, performance improvements, and security patches that come with version 17.2. This ensures the application runs on a more stable and secure database environment.

chore(docker): update Postgres image from 16.6 to 17.2 for improved features and security

---

platform/web/packages/components/src/routes.ts
platform/web/packages/domain/src/Flag/api/index.ts
platform/web/packages/domain/src/Flag/api/query.ts
platform/web/packages/web-app/src/App/menu/index.tsx

- Introduced a new API for flag queries to manage feature toggles and updated menu logic to enable conditional rendering of menu items.
- Improved code readability by cleaning up unnecessary blank lines and refining headerProps formatting.
- Enhanced CatalogueListPage to execute queries only when an identifier is defined and clarified variable naming in CataloguesRouter.

Title: Feature Flags API Integration and Code Refactoring for Readability

---

platform/web/packages/components/src/Wco2Menu/Wco2Menu.tsx
platform/web/packages/components/src/routes.ts
platform/web/packages/web-app/src/App/menu/index.tsx

- Enhanced menu structure with 'Secteur' and 'Systems' submenus for better organization and navigation.
- Ensured route consistency by appending a trailing slash to the catalogues route and cleaned up code by removing unused console logs.
- Added `graph.png` to the public directory to provide a visual element for improved user experience.

Menu Enhancements, Route Consistency, and Visual Improvements

---

.gitignore
infra/docker-compose/config/space-config.json
infra/docker-compose/docker-compose-connect-admin.yml
infra/docker-compose/docker-compose-keycloak.yml
infra/docker-compose/docker-compose-registry-web.yml

- Standardized naming of configuration sources in Docker Compose files for improved clarity and consistency.
- Updated `.gitignore` to exclude `application.*.yml` files, enhancing security by preventing sensitive files from being tracked.

Update Docker Compose Config Source Names and Improve .gitignore

---

infra/docker/keycloak/Dockerfile
platform/web/packages/web-app/src/App/auth/AuthRetryOnError/AuthRetryOnError.tsx
platform/web/packages/web-app/src/App/auth/AuthRetryOnError/index.ts
platform/web/packages/web-app/src/index.tsx

Updated Keycloak theme extraction to support all versions for improved compatibility. Added `AuthRetryOnError` component to enhance authentication retry handling, improving user experience during login failures.

Enhance Keycloak Theme Compatibility and Authentication Retry Handling 

---

.github/workflows/dev.yml
.github/workflows/manual-deploy.yml

The new deployment jobs allow for automated deployments to different environments based on branch and event conditions. This enhances the CI/CD pipeline by ensuring that code is deployed to the appropriate environment automatically, improving the development workflow and reducing manual deployment errors.

feat(workflows): add deployment jobs for dev, preprod, and prod environments in GitHub Actions

---

.github/workflows/deploy.yml

The deployment workflow is enhanced to include separate jobs for non-prod and prod environments. It ensures that the appropriate Docker context exists before deployment, improving reliability and clarity in the deployment process. Additionally, the descriptions are refined for better understanding.

chore(deploy.yml): update deployment workflow to include non-prod and prod environments with context checks

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-release.yml
.github/workflows/deploy-workflow.yml
.github/workflows/dev.yml

The new workflows enable manual deployment to different environments and automate deployment upon release events. This enhances the CI/CD pipeline by providing flexibility in deployment options and ensuring that the application can be deployed consistently across development, pre-production, and production environments.

feat(workflows): add deployment workflows for manual and release processes

---

infra/docker-compose-deploy/config/space-config.json

The roles and permissions have been updated to reflect a new naming convention, replacing old role names with more descriptive ones. New features related to catalogues and configurations are added to enhance functionality and provide clearer access control. This improves maintainability and clarity in the configuration file.

chore(space-config.json): update roles and permissions to align with new naming conventions and add new features

---

platform/infra/redis/src/main/kotlin/io/komune/registry/infra/redis/RegistryS2SourcingSpringDataAdapter.kt

The code now catches JedisDataException during the counting of the entity stream, logging an error message and returning 0 instead of allowing the application to crash. This improves the robustness of the application by ensuring it can handle potential data access issues gracefully.

fix(redis): handle JedisDataException when counting entity stream to prevent application crashes

---

platform/script/script-import/src/main/kotlin/io/komune/registry/script/imports/ImportScript.kt
platform/web/packages/web-app/public/env-config.local.js
platform/web/packages/web-app/src/App/menu/index.tsx

The changes remove unnecessary code and improve the handling of image URLs in the menu component. Unused logo configuration is deleted from the environment config, and the image URL construction logic is enhanced to ensure proper formatting, which helps prevent potential issues with image loading.

chore: clean up unused code and improve image URL handling in the webapp

---

infra/docker-compose/docker-compose-redis.yml
platform/data/f2/catalogue-f2/catalogue-f2-api/src/main/resources/catalogues/100m-chart.json
platform/script/script-import/src/main/kotlin/io/komune/registry/script/imports/ImportRepository.kt
platform/script/script-import/src/main/kotlin/io/komune/registry/script/imports/ImportScript.kt
platform/script/script-import/src/main/kotlin/io/komune/registry/script/imports/model/CatalogueImportSettings.kt
platform/web/packages/domain/src/Catalogue/components/DraftGraphManager/CatalogueGraphManager.tsx
platform/web/packages/domain/src/Catalogue/components/DraftGraphManager/DraftGraphManager.tsx
platform/web/packages/domain/src/Dataset/components/DatasetRouterSection.tsx
platform/web/packages/rawGraph/src/Chart/BarChart.js
platform/web/packages/rawGraph/src/Chart/LineChart.js
platform/web/packages/rawGraph/src/Chart/PieChart.js
platform/web/packages/rawGraph/src/chart.js
platform/web/packages/web-app/src/App/menu/index.tsx

Update dataset type from "graph" to "graphs" for consistency.
Add initDataset function to streamline dataset initialization.
Implement importDistribution function for better media handling.
Enhance dataset settings model to include media configurations.
Add custom PieChart component for enhanced data visualization.
Clean up console logs for better code quality.

Enhance Dataset Initialization and Media Handling

---

platform/data/f2/dataset-f2/dataset-f2-api/src/main/kotlin/io/komune/registry/f2/dataset/api/service/DatasetF2FinderService.kt

The dataset retrieval logic now checks for access rights based on the catalogue's visibility. It ensures that public catalogues are accessible to all, while private catalogues can only be accessed by their respective owner organizations. This change improves data security and ensures that users only access datasets they are authorized to view.

feat(DatasetF2FinderService.kt): enhance dataset retrieval logic to include access rights checks

---

platform/web/packages/keycloak/public/env-config.local.js

The environment configuration is updated to include a legal notice URL and sponsor information, enhancing the application's ability to display relevant legal and sponsorship content. The platform URL is also restructured for better organization and clarity.

feat(env-config.local.js): restructure environment configuration to include legal notice and sponsor details

---

platform/script/script-gateway/src/main/resources/application.yml
platform/web/packages/web-app/public/locales/en/translation.json
platform/web/packages/web-app/public/locales/es/translation.json
platform/web/packages/web-app/public/locales/fr/translation.json

fix(translation): update CO₂ translations to a more concise format in English, Spanish, and French Commenting out the source configuration in application.yml prevents potential issues during initialization. The translation updates improve clarity and conciseness in the user interface by simplifying the CO₂ saved descriptions across multiple languages.

update CO₂ translations 

---

README.md

The README now provides a more engaging introduction to the `trace-registry` project, explaining its purpose and the importance of organizing information. It outlines the main goals and key concepts, making it easier for users to understand the project's structure and functionality. This improves the overall documentation quality and helps new users quickly grasp the project's objectives.

docs(README.md): enhance project description and structure for clarity and engagement

---

platform/web/package.json
platform/web/yarn.lock

Updating the @komune-io/g2 dependency to a newer version ensures that the application benefits from the latest features, improvements, and bug fixes provided by the library.

chore(package.json): update @komune-io/g2 dependency to version 0.8.0-alpha.6cd0e12 for improved features and bug fixes

---

infra/http/api.http
platform/data/f2/catalogue-f2/catalogue-f2-api/src/main/kotlin/io/komune/registry/f2/catalogue/api/CatalogueEndpoint.kt
platform/data/f2/catalogue-f2/catalogue-f2-api/src/main/kotlin/io/komune/registry/f2/catalogue/api/service/CatalogueF2FinderService.kt
platform/data/f2/catalogue-f2/catalogue-f2-domain/src/commonMain/kotlin/io/komune/registry/f2/catalogue/domain/query/CatalogueGetHistoryDTO.kt

Improves API security by parameterizing client credentials, adds actual version to catalogue history results, and refines history retrieval with proper time-based sorting in the underlying services.

Enhance catalogue history API and improve authentication security

---

platform/web/package.json
platform/web/yarn.lock

Updates the @komune-io/g2 package dependency to version 0.8.0 to incorporate the latest improvements, bug fixes, and new features, ensuring better stability and enhanced functionality.

Update @komune-io/g2 library to version 0.8.0
