- infra/docker-compose/docker-compose-keycloak.yml
Updated KC_DB_URL to reference the POSTGRES_KEYCLOAK_DB environment variable, ensuring the correct database name for Keycloak.
Improves configuration clarity and ensures proper management of database connections.
> use POSTGRES_KEYCLOAK_DB for database name

- .gitignore
The addition of **/env-config.js to the .gitignore file ensures that sensitive configuration files are not tracked by Git, reducing the risk of exposing sensitive information in version control.
> chore(.gitignore): add env-config.js to .gitignore to prevent sensitive data exposure

- Makefile_docker.mk
The target name is updated to better reflect its purpose, aligning it with the associated Docker image being built and published. This change enhances the readability and maintainability of the Makefile.
> 3chore(Makefile_docker.mk): rename docker-keycloak-auth-publish target to docker-postgres-publish for clarity

- .dockerignore
- .env_version
- Makefile_docker.mk
- infra/docker/keycloak/Dockerfile
- platform/data/dsl/dcat/src/jvmTest/kotlin/io/komune/registry/dsl/dcat/domain/model/model/CatalogDslTestJvm.kt
- platform/data/dsl/dcat/src/jvmTest/kotlin/io/komune/registry/dsl/dcat/domain/model/model/DatasetDslTest.kt
- platform/data/dsl/dcat/src/jvmTest/kotlin/io/komune/registry/dsl/dcat/domain/model/model/StandardsCatalogueTest.kt
- platform/data/dsl/dcat/src/jvmTest/kotlin/io/komune/registry/dsl/dcat/domain/model/model/model/CatalogDslTest.kt
- platform/web/packages/keycloak/package.json
- platform/web/packages/web-app/src/App/pages/Catalogue/CataloguesRouter/CataloguesRouter.tsx
- platform/web/yarn.lock
- Removed infra from `.dockerignore` to include infrastructure files in the Docker image for proper containerization.
- Introduced Keycloak Docker support, added configuration, and corrected spelling of "registry" in the Keycloak package name.
- Renamed package from `keycloakify-starter` to `registry-keycloakify` and updated description; also, changed query identifier key in `CataloguesRouter` for consistency.
- Added `language` property to catalogues and datasets in tests to support multilingual capabilities for internationalization.
> Add Language Property in Tests for Multilingual Support

- .github/workflows/dev.yml
- Makefile_docker.mk
The Makefile is updated to include targets for linting, building, and publishing Keycloak components. This addition ensures that the Keycloak service is properly integrated into the build process, promoting consistency and quality across all services in the application.
> feat(Makefile_docker.mk): add keycloak linting, building, and publishing targets to the Makefile

- platform/web/packages/keycloak/index.html
The versioning query parameter is removed from the script source to simplify the loading of the env-config.js file. This change ensures that the script is always loaded without versioning, which can help avoid caching issues during development.
> fix(index.html): remove versioning from env-config.js script source

- platform/web/packages/keycloak/src/login/api/command.ts
The command path for user onboarding is modified to include the 'identity/' prefix, ensuring that the API request is routed correctly to the intended endpoint. This change resolves potential issues with API calls not reaching the correct service.
> fix(command.ts): update userOnboard command path to include identity prefix for correct API routing

- platform/web/packages/web-app/src/App/pages/router.tsx
The default route now renders the CataloguesRouter instead of the ProjectList. This change is made to prioritize the catalogues feature in the application, enhancing user navigation and experience by directing users to the catalogues section upon accessing the root path.
> feat(router.tsx): replace ProjectList with CataloguesRouter as the default route element

- platform/web/packages/keycloak/src/login/Pages/Register.tsx
The checkbox field is renamed to better reflect its purpose, which is to allow users to opt-in for a newsletter. This change enhances the user experience by providing clearer options during the registration process.
> fix(Register.tsx): rename checkbox field from acceptChart100M to acceptNewsletter for clarity

- platform/script/script-import/src/main/kotlin/io/komune/registry/script/imports/ImportScript.kt
- platform/web/packages/domain/src/Catalogue/components/CatalogueResultList/CatalogueResultList.tsx
The path for matchedPathToActualPath is changed from datasetAddMediaDistribution to datasetDownloadDistribution to accurately represent the operation being performed. This ensures that the application correctly references the intended dataset download functionality.
> fix(ImportScript.kt): update path for matchedPathToActualPath to reflect correct dataset operation

- .github/workflows/deploy.yml
The input type for run_reset is changed to string to ensure compatibility with the GitHub Actions input handling, as it allows for better flexibility in parsing and managing input values. This change prevents potential issues with type mismatches during workflow execution.
> fix(deploy.yml): change type of run_reset input from boolean to string for compatibility

- .github/workflows/deploy.yml
The addition of the SSH key setup step allows the GitHub Actions workflow to securely access the Docker context. This is necessary for operations that require authentication, ensuring that the deployment process can interact with private repositories or services without exposing sensitive information.
> chore(deploy.yml): add SSH key setup step for GitHub Actions to enable secure access to Docker context

- .github/workflows/deploy.yml
The SSH key is now stored in a dedicated directory `~/.ssh_100m` instead of the default `~/.ssh`. This change helps to avoid potential conflicts with other SSH configurations and improves organization within the GitHub Actions environment. Additionally, the SSH key is added to the SSH agent for better management during the deployment process.
> chore(deploy.yml): update SSH key storage directory for GitHub Actions

- .github/workflows/deploy.yml
The addition of `eval "$(ssh-agent -s)"` initializes the SSH agent, which is necessary for managing SSH keys during the deployment process. This ensures that the SSH key can be added successfully, allowing for secure connections to remote servers.
> chore(deploy.yml): add ssh-agent initialization to the deployment workflow

- .github/workflows/deploy.yml
The secrets declaration for DOCKER_CONTEXT_SSH_KEY is removed as it is not being used in the workflow. This cleanup helps to maintain a clearer and more concise configuration file.
> chore(deploy.yml): remove unnecessary secrets declaration from the workflow

- .github/workflows/deploy.yml
- .github/workflows/dev.yml
The deployment jobs are streamlined by merging the create_env and deploy jobs into a single deploy job. This reduces redundancy and simplifies the workflow configuration. The non-production deployment job is removed to avoid unnecessary complexity, while the environment variable handling is improved for better clarity and maintainability.
> chore(workflows): consolidate deployment jobs and remove redundant configurations

- .github/workflows/deploy.yml
- .github/workflows/manual-deploy.yml
The HOST_NAME_REGISTRY secret is now required in both deploy and manual-deploy workflows to ensure that the necessary hostname configuration is available during deployment. This change enhances the deployment process by making it more robust and configurable.
> feat(workflows): add HOST_NAME_REGISTRY as a required secret for deployment workflows

- .github/workflows/deploy-dev.yml
The path to the deployment workflow is corrected to ensure that the GitHub Actions can locate and execute the appropriate workflow file during the manual deployment process. This change prevents potential errors in the deployment pipeline.
> chore(deploy-dev.yml): update workflow reference to use the correct path for the deployment workflow

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-release.yml
The names of the workflows have been changed to better reflect their purpose. "Manual Deployment" is now "Deployment Manual" and "Release Workflow" is now "Deployment Release." Additionally, the environment for the release workflow has been updated from "rod" to "prod" to align with standard production naming conventions. These changes enhance clarity and maintain consistency across the workflow files.
> chore(workflows): update workflow names for clarity and consistency

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-release.yml
The workflows for deploying to development, pre-production, and production environments now explicitly reference the main branch of the deploy-workflow.yml file. This ensures that the latest changes in the deployment workflow are used, improving consistency and reliability in the deployment process.
> chore(workflows): specify the main branch for deploy-workflow.yml usage in GitHub Actions

- platform/identity/f2/user-f2/user-f2-api/src/main/kotlin/io/komune/registry/f2/user/api/config/OnboardingConfig.kt
The property placeholders for default roles are changed from camel case to hyphenated format to align with the naming conventions used in the configuration files. This improves readability and consistency across the application configuration.
> fix(OnboardingConfig.kt): update property placeholders to use hyphens instead of camel case for consistency

- platform/web/packages/keycloak/src/login/Pages/LoginConfigTotp.tsx
The totpSecret is now included in the initialValues to ensure it is part of the component's state management. Additionally, adding the key for totpSecret in the form fields allows for better handling and validation of the TOTP secret, improving the overall user experience during the login configuration process.
> feat(LoginConfigTotp): add totpSecret to initialValues and form fields for TOTP configuration

- infra/docker-compose/config/space-config.json
- platform/data/s2/catalogue-draft/catalogue-draft-api/src/main/kotlin/io/komune/registry/s2/catalogue/draft/api/entity/CatalogueDraftSnapMeiliSearchRepository.kt
feat(catalogue-draft): inject CatalogueAutomateConfig into CatalogueDraftSnapMeiliSearchRepository for improved configuration management The JSON features array is reformatted to enhance readability and maintainability. The CatalogueDraftSnapMeiliSearchRepository now uses CatalogueAutomateConfig to manage configurations, allowing for better separation of concerns and easier adjustments to the repository's behavior based on configuration changes.
> chore(docker-compose): format JSON features array for better readability

- Makefile_libs.mk
- platform/data/f2/dataset-f2/dataset-f2-api/src/main/kotlin/io/komune/registry/f2/dataset/api/DatasetEndpoint.kt
Adding the --refresh-dependencies flag to the build command ensures that all dependencies are updated to their latest versions. This change helps to avoid potential issues with outdated dependencies and improves the reliability of the build process.
> chore(Makefile_libs.mk): update build command to include --refresh-dependencies flag

- platform/script/script-import/src/main/kotlin/io/komune/registry/script/imports/ImportScript.kt
- platform/web/packages/keycloak/src/login/i18n.ts
Ensure registry path handling always ends with a slash to prevent potential issues with path concatenation.
Add translations for the "Reset your password?" title in English, French, and Spanish to enhance user experience and accessibility.
> Correct Registry Path Handling and Add Translations for Email Forgot Title

- platform/data/f2/catalogue-f2/catalogue-f2-api/src/main/kotlin/io/komune/registry/f2/catalogue/api/service/CatalogueF2AggregateService.kt
- platform/script/script-import/src/main/kotlin/io/komune/registry/script/imports/ImportScript.kt
The changes streamline the catalogue creation and update process by consolidating logic into the `getOrCreate` method. This reduces code duplication and enhances clarity. The import process is also improved by using `flatMapIndexed` for better handling of catalogue initialization, ensuring that existing catalogues are skipped efficiently.
> refactor(catalogue-f2-api): simplify catalogue creation and update logic for better readability and maintainability

- platform/script/script-import/src/main/kotlin/io/komune/registry/script/imports/ImportScript.kt
Improves code readability by changing the lambda parameter name from `it` to `dataset`. This makes it clearer what the parameter represents, enhancing maintainability and understanding of the code.
> refactor(ImportScript.kt): rename lambda parameter for clarity in dataset mapping

- platform/web/packages/components/src/LexicalEditor/plugins/ImagesPlugin/UploadImageModal.tsx
- platform/web/packages/components/src/dataset/GraphGallery/GraphGallery.tsx
- platform/web/packages/components/src/dataset/GraphGallery/index.ts
- platform/web/packages/components/src/dataset/ResourceGallery/ResourceGallery.tsx
- platform/web/packages/components/src/dataset/ResourceGallery/index.ts
- platform/web/packages/components/src/dataset/index.ts
feat(GraphGallery): create GraphGallery component to display graph datasets
feat(ResourceGallery): create ResourceGallery component to display resource datasets
feat(dataset/index.ts): export GraphGallery and ResourceGallery for easier access
The import statements in `UploadImageModal.tsx` are refactored for better readability. New components `GraphGallery` and `ResourceGallery` are created to encapsulate the logic for displaying graph and resource datasets, respectively. This modular approach enhances code organization and reusability. The `index.ts` file in the dataset directory is updated to export these new components, simplifying their import in other parts of the application.
> feat(UploadImageModal): refactor imports for better readability and organization

- platform/script/script-import/src/main/kotlin/io/komune/registry/script/imports/ImportRepository.kt
- platform/script/script-import/src/main/kotlin/io/komune/registry/script/imports/MarkdownMediaImport.kt
The logging level for several messages is changed from info to debug to reduce log verbosity and ensure that only essential information is logged at the info level. This helps in maintaining cleaner logs while still allowing detailed tracing during debugging sessions.
> style(logging): change logger level from info to debug for detailed logging

- platform/data/f2/catalogue-f2/catalogue-f2-api/src/main/kotlin/io/komune/registry/f2/catalogue/api/service/CatalogueSearchFinderService.kt
The service now checks if the search result items are empty and returns a `CatalogueSearchResult` with an empty list of items. This change improves the API's behavior by providing a clear response when no items are found, enhancing the user experience and preventing potential errors in downstream processing.
> feat(CatalogueSearchFinderService): handle empty search results by returning an empty item list

- platform/data/f2/catalogue-f2/catalogue-f2-api/src/main/kotlin/io/komune/registry/f2/catalogue/api/config/CatalogueConfig.kt
- platform/data/f2/dataset-f2/dataset-f2-api/src/main/kotlin/io/komune/registry/f2/dataset/api/config/DatasetConfig.kt
The changes introduce logging statements that provide visibility into the loading process of type configurations. This helps in debugging and monitoring by informing developers when configurations are being loaded and from which files, enhancing traceability in the application.
> feat(config): add logging for loading type configurations in CatalogueConfig and DatasetConfig classes

- .github/workflows/release.yml
The new workflow allows for manual triggering of a release with specified version and next development version inputs. This enhances the release management process by providing a structured way to handle versioning directly from the GitHub interface.
> chore(release.yml): add GitHub Actions workflow for manual release process

- platform/data/dsl/client/src/jvmMain/kotlin/cccev/dsl/client/DCatGraphClient.kt
- platform/data/f2/license-f2/license-f2-domain/src/commonMain/kotlin/io/komune/registry/f2/license/domain/query/LicenseListQueryDTO.kt
- platform/script/script-import/src/main/kotlin/io/komune/registry/script/imports/ImportRepository.kt
- platform/script/script-import/src/main/kotlin/io/komune/registry/script/imports/ImportScript.kt
- platform/script/script-import/src/main/kotlin/io/komune/registry/script/imports/model/CatalogueImportData.kt
feat(ImportRepository): implement fetchPreExistingLicence to retrieve existing licenses feat(ImportScript): update catalogue creation to include new fields and license handling The changes introduce new fields in the CatalogueDTOBase to enhance the data model, allowing for better representation of catalogues. The `fetchPreExistingLicence` function retrieves existing licenses, improving the import process by ensuring that licenses are correctly associated with catalogues. Additionally, the catalogue creation process is updated to include new fields and handle licenses more effectively, ensuring that all relevant data is captured during imports.
> feat(DCatGraphClient): add new fields to CatalogueDTOBase for enhanced data handling

- platform/web/packages/keycloak/src/config.ts
- platform/web/packages/keycloak/src/login/Template.tsx
- platform/web/packages/keycloak/src/login/i18n.ts
- platform/web/packages/keycloak/src/main.tsx
The configuration now includes optional fields for legal notice and sponsor details. The login template displays this information if provided, enhancing user awareness and promoting sponsors. This change aims to improve transparency and support for the project.
> feat(keycloak): add legal notice and sponsor information to the configuration and login template

- CCCEV.md
The new document outlines the Core Criterion and Core Evidence Vocabulary, detailing its purpose, structure, and usage. It serves as a foundational resource for organizations and individuals to understand and implement the vocabulary for effective information exchange regarding requirements and evidence. This addition enhances the documentation and supports better compliance with standards in data management.
> docs: add Core Criterion and Core Evidence Vocabulary (CCCEV) document to provide a comprehensive framework for data exchang

- infra/http/api.http
- platform/commons/src/commonMain/kotlin/io/komune/registry/s2/commons/history/EventHistory.kt
- platform/data/f2/catalogue-f2/catalogue-f2-api/src/main/kotlin/io/komune/registry/f2/catalogue/api/CatalogueEndpoint.kt
- platform/data/f2/catalogue-f2/catalogue-f2-api/src/main/kotlin/io/komune/registry/f2/catalogue/api/service/CataloguePoliciesEnforcer.kt
- platform/data/f2/catalogue-f2/catalogue-f2-api/src/main/kotlin/io/komune/registry/f2/catalogue/api/service/CataloguePoliciesFilterEnforcer.kt
- platform/data/f2/catalogue-f2/catalogue-f2-client/src/commonMain/kotlin/io/komune/registry/f2/catalogue/client/CatalogueClient.kt
- platform/data/f2/catalogue-f2/catalogue-f2-domain/src/commonMain/kotlin/io/komune/registry/f2/catalogue/domain/CatalogueQueryApi.kt
- platform/data/f2/catalogue-f2/catalogue-f2-domain/src/commonMain/kotlin/io/komune/registry/f2/catalogue/domain/query/CatalogueGetHistoryDTO.kt
- platform/data/s2/catalogue/catalogue-api/build.gradle.kts
- platform/data/s2/catalogue/catalogue-api/src/main/kotlin/io/komune/registry/program/s2/catalogue/api/CatalogueEventWithStateService.kt
- platform/infra/redis/src/main/kotlin/io/komune/registry/infra/redis/EventHistoryService.kt
Implements a new endpoint for fetching catalogue history with supporting components (CatalogueHistoryGetFunction, CatalogueEventWithStateService) and updates the client_id in API requests for proper authentication.
> Add catalogue history feature and update authentication client_id

- infra/http/http-client.env.json
- platform/data/s2/catalogue/catalogue-api/src/main/kotlin/io/komune/registry/program/s2/catalogue/api/CatalogueEventWithStateService.kt
- platform/infra/redis/src/main/kotlin/io/komune/registry/infra/redis/EventHistoryService.kt
Refactors event history services to implement proper time-based sorting functionality and renames development environment from "dev" to "local" for better clarity in configuration files.
> Improve event history sorting and clarify environment naming

- infra/http/api.http
- platform/infra/redis/src/main/kotlin/io/komune/registry/infra/redis/RegistryS2SourcingSpringDataAdapter.kt
Adds a new API endpoint for searching catalogue references with specific parameters and removes a duplicate history replay call in the registry adapter for cleaner, more efficient code execution.
> Add catalogueRefSearch endpoint and fix duplicate history replay
